[package]
name = "ris"
version = "0.1.0"
authors = ["Patrick Chieppe <patrick.chieppe@hotmail.com>"]
edition = "2018"


[dependencies]
regex = "^1.1"
lazy_static = "^1.3"

[dev-dependencies]
pretty_assertions = "^0.6"
version-sync = "^0.7"
